

public class Emails {
	
	final static String[] emails = {
									"e.rmccarty6957@gmail.com",
									"jasonmichael1964@gmail.com",
									"patrick_tanis@hotmail.com",
									"davwardton@gmail.com",
									"patrickkavoo55@gmail.com",
									"midboy24@yahoo.com",
									"tassianoestevao@hotmail.com",
									"yourprairiegold@gmail.com",
									"jeshprsd68@gmail.com",
									"roybraganca@gmail.com",
									"uengzobaer@gmail.com",
									"arandy730@gmail.com",
									"makwinjan@yahoo.com",
									"kauohahou@att.net", 
									"dc49196@gmail.com", 
									"dc49197@gmail.com", 
									"akrzyzak@aol.com", 
									"bosseb94@gmail.com", 
									"georgetingo@gmail.com", 
									"davidpoole67@gmail.com", 
									"drcontresa@hotmail.com", 
									"ted.northwestfurs@gmail.com",
									"jbelfar@gmail.com", 
									"palacinchristian@gmail.com", 
									"atlanticview2004@msn.com", 
									"reg.somers@gmail.com", 
									"robin127@gmail.com",
									"terrylee1348@gmail.com",
									"devaslachanmoolamattom@gmail.com",
									"cranegows@dcsi.net.au",
									"ib_steen@hotmail.com", 
									"somiah@intnet.mu",
									"zavv.henry@gmail.com",
									"chill_bambers07@icloud.com",
									"billchambers@icloud.com",
									"swhharper@gmail.com", 
									"djistice@d3designs.com", 
									"valikhudur@mail.com",
									"an-nar@online.no",
									"dirtburner88@yahoo.com", 
									"clmacman@gmail.com", 
									"jalalirajesh@yahoo.com",
									"thadllc@gmail.com",
									"boolavp@yahoo.com",
									"gzeid30@yahoo.com",
									"sgrmendonca03@gmail.com",
									"kris@ferreri.com", 
									"lennart.nordgren@telia.com",
									"srgmendonca03@gmail.com",
									"csiba68@gmail.com",
									"achaeans@gmail.com",
									"john.0072@hotmail.com",
									"natureboyron02780@yahoo.com",
									"1960jwp@gmail.com",
									"rksasikumar1974@gmail.com",
									"zhizhkaigor@gmail.com",
//									"blairblacker@gmail.com",
//									"mrsannakoffi@yahoo.com",
//									"nathan_dhifa@yahoo.com.au",
//									"dominikhubert7@gmail.com",
//									"natureboyron02780@yahoo.com",
//									"jpdorf007@aol.com",
//									"tony4ssawtell@gmail.com",
//									"Gerikolaj@gmail.com",
//									"shibmook@gmail.com",
//									"donharwood2@gmail.com",
//									"tmacadan@gmail.com",
//									"errikartazurimendiola@gmail.com",
//									"krisdevad55@gmail.com", 
//									"prominent4488@gmail.com",
//									"dc49196@gmail.com",
//									"dogsoldier2412@yahoo.com",
//									"brunoscory79@gmail.com",
//									"wahbi11951@gmail.com",
//									"genjohnwnichols50@outlook.com",
//									"randypapagna@gmail.com",
//									"whitten_dvd@yahoo.com",
//									"diddyhammer@yahoo.com",
//									"ronaldlguest@gmail.com",
//									"georgefrazer777@gmail.com", 
//									"nmooredumjay@gmail.com",
//									"preacherjimmys@gmail.com",
//									"zoranpetrikanovic@gmail.com",
//									"ahmedseyyad@gmail.com",
//									"lorendifri@yahoo.es",
//									"jf32886@gmail.com",
//									"svizzero@gmx.net",
//									"shorten52@gmail.com",
//									"stevenchata500@gmail.com",
//									"zackry46@gmail.com",
//									"F_rany@hotmail.com",
//									"zhizhkaigor@gmail.com",
//									"doc.jonathanfrederick@gmail.com",
//									"dr.raminmoghaddam@gmail.com",
//									"guysting@yahoo.com",
//									"terrydavis7042@yahoo.com",
//									"ahmedbhatk@gmail.com",
//									"jasantanar12@gmail.com",
//									"rskhan614@gmail.com",
//									"bubbal7864u1@gmail.com",
//									"fuaddalla@gmail.com",
//									"stylisch67@googlemail.com",
//									"amougy1202@gmail.com",
//									"Gabrielowen0007@gmail.com",
//									"slavko.bolterstein@gmail.com",
//									"fxpfrengle1956@gmail.com",
//									"jmax8080@gmail.com",
//									"chrismpieterse38@gmail.com",
//									"robertfreestone920@gmail.com",
//									"ta.lejon@live.se",
//									"victorgrandarf@gmail.com",
//									"mfrherman@gmail.com",
//									"srinivasb1210@gmail.com",
//									"prophet.robinson147@gmail.com",
//									"sachindeo747@gmail.com",
//									"hr.clety@gmail.com",
//									"benrichard038@gmail.com",
//									"borian_donchev@abv.bg"
								  };
}
